environment:
    prompt_path: 'examples/education/input/wiki.md'
    tools_file: ''
    database_folder: ''
    database_validators: ''

dataset:
    num_samples: 20
    cost_limit: 3

dialog_manager:
    cost_limit: 2

