environment:
    prompt_path: ''
    tools_folder: ''
    database_folder: ''
    task_description:  # If you don't want to infer you can simply provide it in the field 'content'
        llm:
            type: 'azure'
            name: 'gpt-4o'
        extraction_prompt:
            prompt_hub_name: 'eladlev/task_extraction'

description_generator:
    flow_config:
        prompt:
            prompt_hub_name: 'eladlev/flows_extraction'
    policies_config:
        prompt:
            prompt_hub_name: 'eladlev/policies_extraction'
    edge_config:
        prompt:
            prompt_hub_name: 'eladlev/policies_graph'
        num_workers: 5
    description_config:
        prompt:
            prompt_hub_name: 'eladlev/description_generation'
        num_workers: 5
    refinement_config:
        do_refinement: True # If you don't want to refine the expected behaviour of the descriptions, set this to False
        prompt_feedback:
            prompt_hub_name: 'eladlev/description_refinement'
        prompt_refinement:
            prompt_hub_name: 'eladlev/refined_description2'
        num_workers: 5
    llm_policy:
        type: 'azure'
        name: 'gpt-4o'
    llm_edge:
        type: 'azure'
        name: 'gpt-4o-mini'
    llm_description:
        type: 'azure'
        name: 'gpt-4o'
    llm_refinement:
        type: 'azure'
        name: 'gpt-4o'



